(deftheme madhat2r
  "Created 2018-02-15.")

(custom-theme-set-variables
 'madhat2r
 '(ansi-color-names-vector ["#6f7c80" "#d93334" "#40805b" "#b1951d" "#4f97d7" "#c24160" "#22aae1" "#c1c7c9"]))

(custom-theme-set-faces
 'madhat2r
 '(cursor ((((class color) (min-colors 257)) (:background "#e3dedd")) (((class color) (min-colors 89)) (:background "#d0d0d0"))))
 '(custom-button ((((class color) (min-colors 257)) :background "#1b1e1f" :foreground "#c1c7c9" :box (:line-width 2 :style released-button)) (((class color) (min-colors 89)) :background "#1b1e1f" :foreground "#afd7d7" :box (:line-width 2 :style released-button))))
 '(error ((((class color) (min-colors 257)) (:foreground "#c02e1d")) (((class color) (min-colors 89)) (:foreground "#af0000"))))
 '(font-lock-builtin-face ((((class color) (min-colors 257)) (:foreground "#1395ba")) (((class color) (min-colors 89)) (:foreground "#0087af"))))
 '(font-lock-comment-face ((((class color) (min-colors 257)) (:foreground "#e1c2c2")) (((class color) (min-colors 89)) (:foreground "#e1c2c2"))))
 '(font-lock-constant-face ((((class color) (min-colors 257)) (:foreground "#f16c20")) (((class color) (min-colors 89)) (:foreground "#ff5f00"))))
 '(font-lock-doc-face ((((class color) (min-colors 257)) (:foreground "#555f61")) (((class color) (min-colors 89)) (:foreground "#5f5f5f"))))
 '(font-lock-function-name-face ((((class color) (min-colors 257)) (:foreground "#ecaa38" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#ffff00" :inherit bold))))
 '(font-lock-keyword-face ((((class color) (min-colors 257)) (:inherit bold :foreground "#1395ba")) (((class color) (min-colors 89)) (:inherit bold :foreground "#0087af"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 257)) (:foreground "#f16c20")) (((class color) (min-colors 89)) (:foreground "#ff5f00"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 257)) (:foreground "#ecaa38")) (((class color) (min-colors 89)) (:foreground "#ffff00"))))
 '(font-lock-string-face ((((class color) (min-colors 257)) (:foreground "#a2b86c")) (((class color) (min-colors 89)) (:foreground "green"))))
 '(font-lock-type-face ((((class color) (min-colors 257)) (:foreground "#ef8b2c" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#ff8700" :inherit bold))))
 '(font-lock-variable-name-face ((((class color) (min-colors 257)) (:foreground "#5ca793")) (((class color) (min-colors 89)) (:foreground "#5faf87"))))
 '(font-lock-warning-face ((((class color) (min-colors 257)) (:foreground "#d94e1f" :background "#131516")) (((class color) (min-colors 89)) (:foreground "#d75f00" :background "#131516"))))
 '(fringe ((((class color) (min-colors 257)) (:background "#131516" :foreground "#c1c7c9")) (((class color) (min-colors 89)) (:background "#131516" :foreground "#afd7d7"))))
 '(header-line ((((class color) (min-colors 257)) :background "#0d3c55") (((class color) (min-colors 89)) :background "magenta")))
 '(highlight ((((class color) (min-colors 257)) (:foreground "#c1c7c9" :background "#0d3c55")) (((class color) (min-colors 89)) (:foreground "#afd7d7" :background "#0d3c55"))))
 '(isearch ((((class color) (min-colors 257)) (:foreground "#131516" :background "#f3df91")) (((class color) (min-colors 89)) (:foreground "#131516" :background "#ffd787"))))
 '(lazy-highlight ((((class color) (min-colors 257)) (:underline t :foreground "#f3df91" :weight bold)) (((class color) (min-colors 89)) (:underline t :foreground "#ffd787" :weight bold))))
 '(link ((((class color) (min-colors 257)) (:foreground "#f2f3f4" :underline t)) (((class color) (min-colors 89)) (:foreground "#eeeeee" :underline t))))
 '(link-visited ((((class color) (min-colors 257)) (:foreground "#ebc844" :underline t)) (((class color) (min-colors 89)) (:foreground "#ffd75f" :underline t))))
 '(match ((((class color) (min-colors 257)) (:background "#0d3c55" :foreground "#f3df91")) (((class color) (min-colors 89)) (:background "magenta" :foreground "#f3df91"))))
 '(minibuffer-prompt ((((class color) (min-colors 257)) (:inherit bold :foreground "#1395ba")) (((class color) (min-colors 89)) (:inherit bold :foreground "#0087af"))))
 '(region ((((class color) (min-colors 257)) (:background "#0d3c55")) (((class color) (min-colors 89)) (:background "magenta"))))
 '(secondary-selection ((((class color) (min-colors 257)) (:background "#232628")) (((class color) (min-colors 89)) (:background "#232628"))))
 '(success ((((class color) (min-colors 257)) (:foreground "#9bda34")) (((class color) (min-colors 89)) (:foreground "#afd75f"))))
 '(tooltip ((((class color) (min-colors 257)) (:background "#232628" :foreground "#c1c7c9" :bold nil :italic nil :underline nil)) (((class color) (min-colors 89)) (:background "black" :foreground "#afd7d7" :bold nil :italic nil :underline nil))))
 '(vertical-border ((((class color) (min-colors 257)) (:foreground "#6f7c80")) (((class color) (min-colors 89)) (:foreground "#6f7c80"))))
 '(warning ((((class color) (min-colors 257)) (:foreground "#d94e1f")) (((class color) (min-colors 89)) (:foreground "#d75f00"))))
 '(ahs-face ((((class color) (min-colors 257)) (:underline t :foreground "#f3df91")) (((class color) (min-colors 89)) (:underline t :foreground "#ffd787"))))
 '(ahs-plugin-whole-buffer-face ((((class color) (min-colors 257)) (:background "#f3df91" :foreground "#131516")) (((class color) (min-colors 89)) (:background "#ffd787" :foreground "#131516"))))
 '(message-cited-text ((((class color) (min-colors 257)) (:foreground "#555f61")) (((class color) (min-colors 89)) (:foreground "#5f5f5f"))))
 '(message-header-other ((((class color) (min-colors 257)) (:foreground "#c1c7c9" :background nil :weight normal)) (((class color) (min-colors 89)) (:foreground "#afd7d7" :background nil :weight normal))))
 '(message-header-subject ((((class color) (min-colors 257)) (:inherit message-header-other :weight bold :foreground "#5ca793")) (((class color) (min-colors 89)) (:inherit message-header-other :weight bold :foreground "#5ca793"))))
 '(message-header-to ((((class color) (min-colors 257)) (:inherit message-header-other :weight bold :foreground "#f16c20")) (((class color) (min-colors 89)) (:inherit message-header-other :weight bold :foreground "#ff5f00"))))
 '(message-header-cc ((((class color) (min-colors 257)) (:inherit message-header-to)) (((class color) (min-colors 89)) (:inherit message-header-to))))
 '(message-header-name ((((class color) (min-colors 257)) (:foreground "#1395ba")) (((class color) (min-colors 89)) (:foreground "#0087af"))))
 '(message-header-newsgroups ((((class color) (min-colors 257)) (:foreground "#22aae1" :slant normal)) (((class color) (min-colors 89)) (:foreground "#22aae1" :slant normal))))
 '(message-separator ((((class color) (min-colors 257)) (:foreground "#555f61")) (((class color) (min-colors 89)) (:foreground "#5f5f5f"))))
 '(message-mml ((((class color) (min-colors 257)) (:foreground "#6f7c80" :background "#232628")) (((class color) (min-colors 89)) (:foreground "#6f7c80" :background "#232628"))))
 '(company-echo-common ((((class color) (min-colors 257)) (:background "#c1c7c9" :foreground "#131516")) (((class color) (min-colors 89)) (:background "#afd7d7" :foreground "#131516"))))
 '(company-preview ((((class color) (min-colors 257)) (:background "#232628" :foreground "#c1c7c9")) (((class color) (min-colors 89)) (:background "black" :foreground "#afd7d7"))))
 '(company-preview-common ((((class color) (min-colors 257)) (:background "#232628" :foreground "#ebc844")) (((class color) (min-colors 89)) (:background "black" :foreground "#ffd75f"))))
 '(company-preview-search ((((class color) (min-colors 257)) (:foreground "#f16c20")) (((class color) (min-colors 89)) (:foreground "#ff5f00"))))
 '(company-scrollbar-bg ((((class color) (min-colors 257)) (:background "#1b1e1f")) (((class color) (min-colors 89)) (:background "black"))))
 '(company-scrollbar-fg ((((class color) (min-colors 257)) (:background "#131516")) (((class color) (min-colors 89)) (:background "black"))))
 '(company-template-field ((((class color) (min-colors 257)) (:inherit region)) (((class color) (min-colors 89)) (:inherit region))))
 '(company-tooltip ((((class color) (min-colors 257)) (:background "#232628" :foreground "#c1c7c9")) (((class color) (min-colors 89)) (:background "black" :foreground "#afd7d7"))))
 '(company-tooltip-annotation ((((class color) (min-colors 257)) (:foreground "#1395ba")) (((class color) (min-colors 89)) (:foreground "#0087af"))))
 '(company-tooltip-annotation-selection ((((class color) (min-colors 257)) (:foreground "#1395ba")) (((class color) (min-colors 89)) (:foreground "#0087af"))))
 '(company-tooltip-common ((((class color) (min-colors 257)) (:background "#232628" :foreground "#ebc844")) (((class color) (min-colors 89)) (:background "black" :foreground "#ffd75f"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 257)) (:foreground "#ebc844")) (((class color) (min-colors 89)) (:foreground "#ffd75f"))))
 '(company-tooltip-mouse ((((class color) (min-colors 257)) (:inherit highlight)) (((class color) (min-colors 89)) (:inherit highlight-term))))
 '(company-tooltip-search ((((class color) (min-colors 257)) (:foreground "#f16c20")) (((class color) (min-colors 89)) (:foreground "#ff5f00"))))
 '(company-tooltip-search-selection ((((class color) (min-colors 257)) (:foreground "#f16c20")) (((class color) (min-colors 89)) (:foreground "#ff5f00"))))
 '(company-tooltip-selection ((((class color) (min-colors 257)) (:background "#44505c" :foreground "#c1c7c9")) (((class color) (min-colors 89)) (:background "#5f5f5f" :foreground "#afd7d7"))))
 '(diff-added ((((class color) (min-colors 257)) :background nil :foreground "#40805b") (((class color) (min-colors 89)) :background nil :foreground "#40805b")))
 '(diff-changed ((((class color) (min-colors 257)) :background nil :foreground "#1395ba") (((class color) (min-colors 89)) :background nil :foreground "#0087af")))
 '(diff-header ((((class color) (min-colors 257)) :background "#232628" :foreground "#ecaa38") (((class color) (min-colors 89)) :background "#232628" :foreground "#ffff00")))
 '(diff-indicator-added ((((class color) (min-colors 257)) :background nil :foreground "#40805b") (((class color) (min-colors 89)) :background nil :foreground "#40805b")))
 '(diff-indicator-changed ((((class color) (min-colors 257)) :background nil :foreground "#1395ba") (((class color) (min-colors 89)) :background nil :foreground "#0087af")))
 '(diff-indicator-removed ((((class color) (min-colors 257)) :background nil :foreground "#d93334") (((class color) (min-colors 89)) :background nil :foreground "#d93334")))
 '(diff-refine-added ((((class color) (min-colors 257)) :background "#40805b" :foreground "#6f7c80") (((class color) (min-colors 89)) :background "#40805b" :foreground "#6f7c80")))
 '(diff-refine-changed ((((class color) (min-colors 257)) :background "#1395ba" :foreground "#6f7c80") (((class color) (min-colors 89)) :background "#0087af" :foreground "#6f7c80")))
 '(diff-refine-removed ((((class color) (min-colors 257)) :background "#d93334" :foreground "#6f7c80") (((class color) (min-colors 89)) :background "#d93334" :foreground "#6f7c80")))
 '(diff-removed ((((class color) (min-colors 257)) :background nil :foreground "#d93334") (((class color) (min-colors 89)) :background nil :foreground "#d93334")))
 '(dired-directory ((((class color) (min-colors 257)) (:foreground "#1395ba" :background "#131516" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#0087af" :background "#131516" :inherit bold))))
 '(dired-flagged ((((class color) (min-colors 257)) (:foreground "#d93334")) (((class color) (min-colors 89)) (:foreground "#d93334"))))
 '(dired-header ((((class color) (min-colors 257)) (:foreground "#ebc844" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#ffd75f" :inherit bold))))
 '(dired-ignored ((((class color) (min-colors 257)) (:inherit shadow)) (((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 257)) (:foreground "#ebc844" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#ffd75f" :inherit bold))))
 '(dired-marked ((((class color) (min-colors 257)) (:foreground "#c24160" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#c24160" :inherit bold))))
 '(dired-perm-write ((((class color) (min-colors 257)) (:foreground "#c1c7c9" :underline t)) (((class color) (min-colors 89)) (:foreground "#afd7d7" :underline t))))
 '(dired-symlink ((((class color) (min-colors 257)) (:foreground "#22aae1" :background "#131516" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#22aae1" :background "#131516" :inherit bold))))
 '(dired-warning ((((class color) (min-colors 257)) (:foreground "#d94e1f")) (((class color) (min-colors 89)) (:foreground "#d75f00"))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 257)) (:foreground "#f3df91" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#ffd787" :inherit bold))))
 '(flycheck-error ((((supports :underline (:style line)) (class color) (min-colors 257)) (:underline (:style line :color "#c02e1d"))) (((class color) (min-colors 257)) (:foreground "#c1c7c9" :background "#c02e1d" :inherit bold :underline t))))
 '(flycheck-error-list-checker-name ((((class color) (min-colors 257)) (:foreground "#1395ba")) (((class color) (min-colors 89)) (:foreground "#0087af"))))
 '(flycheck-fringe-error ((((class color) (min-colors 257)) (:foreground "#c02e1d" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#af0000" :inherit bold))))
 '(flycheck-fringe-info ((((class color) (min-colors 257)) (:foreground "#1395ba" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#0087af" :inherit bold))))
 '(flycheck-fringe-warning ((((class color) (min-colors 257)) (:foreground "#d94e1f" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#d75f00" :inherit bold))))
 '(flycheck-info ((((supports :underline (:style line)) (class color) (min-colors 257)) (:underline (:style line :color "#1395ba"))) (((class color) (min-colors 257)) (:foreground "#c1c7c9" :background "#1395ba" :inherit bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style line)) (class color) (min-colors 257)) (:underline (:style line :color "#d94e1f"))) (((class color) (min-colors 257)) (:foreground "#c1c7c9" :background "#d94e1f" :inherit bold :underline t))))
 '(helm-buffer-directory ((((class color) (min-colors 257)) (:foreground "#c1c7c9" :background "#131516")) (((class color) (min-colors 89)) (:foreground "#afd7d7" :background "#131516"))))
 '(helm-buffer-file ((((class color) (min-colors 257)) (:foreground "#c1c7c9" :background "#131516")) (((class color) (min-colors 89)) (:foreground "#afd7d7" :background "#131516"))))
 '(helm-buffer-not-saved ((((class color) (min-colors 257)) (:foreground "#ebc844" :background "#131516")) (((class color) (min-colors 89)) (:foreground "#ffd75f" :background "#131516"))))
 '(helm-buffer-process ((((class color) (min-colors 257)) (:foreground "#1395ba" :background "#131516")) (((class color) (min-colors 89)) (:foreground "#0087af" :background "#131516"))))
 '(helm-buffer-saved-out ((((class color) (min-colors 257)) (:foreground "#c1c7c9" :background "#131516")) (((class color) (min-colors 89)) (:foreground "#afd7d7" :background "#131516"))))
 '(helm-buffer-size ((((class color) (min-colors 257)) (:foreground "#c1c7c9" :background "#131516")) (((class color) (min-colors 89)) (:foreground "#afd7d7" :background "#131516"))))
 '(helm-candidate-number ((((class color) (min-colors 257)) (:background "#131516" :foreground "#1395ba" :inherit bold)) (((class color) (min-colors 89)) (:background "#131516" :foreground "#0087af" :inherit bold))))
 '(helm-ff-directory ((((class color) (min-colors 257)) (:foreground "#1395ba" :background "#131516" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#0087af" :background "#131516" :inherit bold))))
 '(helm-ff-dotted-directory ((((class color) (min-colors 257)) (:foreground "#1395ba" :background "#131516" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#0087af" :background "#131516" :inherit bold))))
 '(helm-ff-dotted-symlink-directory ((((class color) (min-colors 257)) (:foreground "#22aae1" :background "#131516" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#22aae1" :background "#131516" :inherit bold))))
 '(helm-ff-executable ((((class color) (min-colors 257)) (:foreground "#9bda34" :background "#131516" :weight normal)) (((class color) (min-colors 89)) (:foreground "#afd75f" :background "#131516" :weight normal))))
 '(helm-ff-file ((((class color) (min-colors 257)) (:foreground "#c1c7c9" :background "#131516" :weight normal)) (((class color) (min-colors 89)) (:foreground "#afd7d7" :background "#131516" :weight normal))))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 257)) (:foreground "#d93334" :background "#131516" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#d93334" :background "#131516" :inherit bold))))
 '(helm-ff-prefix ((((class color) (min-colors 257)) (:foreground "#131516" :background "#1395ba" :weight normal)) (((class color) (min-colors 89)) (:foreground "#131516" :background "#0087af" :weight normal))))
 '(helm-ff-symlink ((((class color) (min-colors 257)) (:foreground "#22aae1" :background "#131516" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#22aae1" :background "#131516" :inherit bold))))
 '(helm-grep-cmd-line ((((class color) (min-colors 257)) (:foreground "#c1c7c9" :background "#131516")) (((class color) (min-colors 89)) (:foreground "#afd7d7" :background "#131516"))))
 '(helm-grep-file ((((class color) (min-colors 257)) (:foreground "#c1c7c9" :background "#131516")) (((class color) (min-colors 89)) (:foreground "#afd7d7" :background "#131516"))))
 '(helm-grep-finish ((((class color) (min-colors 257)) (:foreground "#c1c7c9" :background "#131516")) (((class color) (min-colors 89)) (:foreground "#afd7d7" :background "#131516"))))
 '(helm-grep-lineno ((((class color) (min-colors 257)) (:foreground "#ef8b2c" :background "#131516" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#ff8700" :background "#131516" :inherit bold))))
 '(helm-grep-match ((((class color) (min-colors 257)) (:foreground nil :background nil :inherit helm-match)) (((class color) (min-colors 89)) (:foreground nil :background nil :inherit helm-match))))
 '(helm-header ((((class color) (min-colors 257)) (:foreground "#c1c7c9" :background "#131516" :underline nil :box nil)) (((class color) (min-colors 89)) (:foreground "#afd7d7" :background "#131516" :underline nil :box nil))))
 '(helm-header-line-left-margin ((((class color) (min-colors 257)) (:foreground "#1395ba" :background nil)) (((class color) (min-colors 89)) (:foreground "#0087af" :background nil))))
 '(helm-match ((((class color) (min-colors 257)) (:background "#1b1e1f" :foreground "#ebc844")) (((class color) (min-colors 89)) (:background "#1b1e1f" :foreground "#ebc844"))))
 '(helm-match-item ((((class color) (min-colors 257)) (:background "#1b1e1f" :foreground "#ebc844")) (((class color) (min-colors 89)) (:background "#1b1e1f" :foreground "#ebc844"))))
 '(helm-moccur-buffer ((((class color) (min-colors 257)) (:foreground "#5ca793" :background "#131516")) (((class color) (min-colors 89)) (:foreground "#5faf87" :background "#131516"))))
 '(helm-selection ((((class color) (min-colors 257)) (:background "#0d3c55")) (((class color) (min-colors 89)) (:background "magenta"))))
 '(helm-selection-line ((((class color) (min-colors 257)) (:background "#1b1e1f")) (((class color) (min-colors 89)) (:background "#1b1e1f"))))
 '(helm-separator ((((class color) (min-colors 257)) (:foreground "#ebc844" :background "#131516")) (((class color) (min-colors 89)) (:foreground "#ffd75f" :background "#131516"))))
 '(helm-source-header ((((class color) (min-colors 257)) (:background "#ebc844" :foreground "#131516" :inherit bold)) (((class color) (min-colors 89)) (:background "#ffd75f" :foreground "#131516" :inherit bold))))
 '(helm-visible-mark ((((class color) (min-colors 257)) (:foreground "#1395ba" :background "#232628")) (((class color) (min-colors 89)) (:foreground "#0087af" :background "#232628"))))
 '(info-header-xref ((((class color) (min-colors 257)) (:foreground "#ecaa38" :underline t)) (((class color) (min-colors 89)) (:foreground "#ffff00" :underline t))))
 '(info-xref ((((class color) (min-colors 257)) (:foreground "#ebc844" :underline t)) (((class color) (min-colors 89)) (:foreground "#ffd75f" :underline t))))
 '(info-node ((((class color) (min-colors 257)) (:foreground "#ecaa38" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#ffff00" :inherit bold))))
 '(info-title-1 ((((class color) (min-colors 257)) (:height 1.4 :inherit bold)) (((class color) (min-colors 89)) (:height 1.4 :inherit bold))))
 '(info-title-2 ((((class color) (min-colors 257)) (:height 1.3 :inherit bold)) (((class color) (min-colors 89)) (:height 1.3 :inherit bold))))
 '(info-title-3 ((((class color) (min-colors 257)) (:height 1.3)) (((class color) (min-colors 89)) (:height 1.3))))
 '(info-title-4 ((((class color) (min-colors 257)) (:height 1.2)) (((class color) (min-colors 89)) (:height 1.2))))
 '(linum ((t (:background "#232628" :foreground "#e3dedd"))))
 '(magit-blame-name ((((class color) (min-colors 257)) :background "#32322c" :foreground "#b1951d") (((class color) (min-colors 89)) :background "#32322c" :foreground "#875f00")))
 '(magit-blame-heading ((((class color) (min-colors 257)) :background "#32322c" :foreground "#40805b") (((class color) (min-colors 89)) :background "#32322c" :foreground "#40805b")))
 '(magit-blame-hash ((((class color) (min-colors 257)) :background "#32322c" :foreground "#ecaa38") (((class color) (min-colors 89)) :background "#32322c" :foreground "#ffff00")))
 '(magit-blame-summary ((((class color) (min-colors 257)) :background "#32322c" :foreground "#b1951d") (((class color) (min-colors 89)) :background "#32322c" :foreground "#875f00")))
 '(magit-blame-date ((((class color) (min-colors 257)) :background "#32322c" :foreground "#40805b") (((class color) (min-colors 89)) :background "#32322c" :foreground "#40805b")))
 '(magit-branch-current ((((class color) (min-colors 257)) (:background "#293239" :foreground "#4f97d7" :inherit bold :box t)) (((class color) (min-colors 89)) (:background "#293239" :foreground "#268bd2" :inherit bold :box t))))
 '(magit-branch-local ((((class color) (min-colors 257)) (:background "#293239" :foreground "#4f97d7" :inherit bold)) (((class color) (min-colors 89)) (:background "#293239" :foreground "#268bd2" :inherit bold))))
 '(magit-branch-remote ((((class color) (min-colors 257)) (:background "#293235" :foreground "#10A585" :inherit bold)) (((class color) (min-colors 89)) (:background "#293235" :foreground "#10A585" :inherit bold))))
 '(magit-diff-context-highlight ((((class color) (min-colors 257)) (:background "#1b1e1f" :foreground "#c1c7c9")) (((class color) (min-colors 89)) (:background "#1b1e1f" :foreground "#afd7d7"))))
 '(magit-diff-file-heading ((((class color) (min-colors 257)) (:background "#373d3f" :foreground "#555f61")) (((class color) (min-colors 89)) (:background "#373d3f" :foreground "#5f5f5f"))))
 '(magit-diff-file-heading-highlight ((((class color) (min-colors 257)) (:background "#373d3f" :foreground "#555f61")) (((class color) (min-colors 89)) (:background "#373d3f" :foreground "#5f5f5f"))))
 '(magit-diff-hunk-heading ((((class color) (min-colors 257)) (:background "#0d3c55" :foreground "#c1c7c9")) (((class color) (min-colors 89)) (:background "#0d3c55" :foreground "#afd7d7"))))
 '(magit-diff-hunk-heading-highlight ((((class color) (min-colors 257)) (:background "#0d3c55" :foreground "#c1c7c9")) (((class color) (min-colors 89)) (:background "#0d3c55" :foreground "#afd7d7"))))
 '(magit-hash ((((class color) (min-colors 257)) (:foreground "#5ca793")) (((class color) (min-colors 89)) (:foreground "#5faf87"))))
 '(magit-log-author ((((class color) (min-colors 257)) (:foreground "#ecaa38")) (((class color) (min-colors 89)) (:foreground "#ffff00"))))
 '(magit-process-ng ((((class color) (min-colors 257)) (:foreground "#d94e1f" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#d75f00" :inherit bold))))
 '(magit-process-ok ((((class color) (min-colors 257)) (:foreground "#ecaa38" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#ffff00" :inherit bold))))
 '(magit-section-heading ((((class color) (min-colors 257)) (:foreground "#1395ba" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#0087af" :inherit bold))))
 '(magit-section-highlight ((((class color) (min-colors 257)) (:background "#1b1e1f")) (((class color) (min-colors 89)) (:background "#1b1e1f"))))
 '(markdown-header-face-1 ((((class color) (min-colors 257)) (:inherit bold :foreground "#ebc844" :height 1.0)) (((class color) (min-colors 89)) (:inherit bold :foreground "#ebc844" :height 1.0))))
 '(markdown-header-face-2 ((((class color) (min-colors 257)) (:inherit bold :foreground "#0f5b78" :height 1.0)) (((class color) (min-colors 89)) (:inherit bold :foreground "#0f5b78" :height 1.0))))
 '(markdown-header-face-3 ((((class color) (min-colors 257)) (:bold nil :foreground "#5ca793" :height 1.0)) (((class color) (min-colors 89)) (:bold nil :foreground "#5ca793" :height 1.0))))
 '(markdown-header-face-4 ((((class color) (min-colors 257)) (:bold nil :foreground "#1395ba")) (((class color) (min-colors 89)) (:bold nil :foreground "#1395ba"))))
 '(markdown-header-face-5 ((((class color) (min-colors 257)) (:bold nil :foreground "#ebc844")) (((class color) (min-colors 89)) (:bold nil :foreground "#ebc844"))))
 '(markdown-header-face-6 ((((class color) (min-colors 257)) (:bold nil :foreground "#0f5b78")) (((class color) (min-colors 89)) (:bold nil :foreground "#0f5b78"))))
 '(mode-line ((((class color) (min-colors 257)) (:foreground "#c1c7c9" :background "#373d3f" :box (:color "#0d3c55" :line-width 1))) (((class color) (min-colors 89)) (:foreground "#afd7d7" :background "#373d3f" :box (:color "#0d3c55" :line-width 1)))))
 '(mode-line-inactive ((((class color) (min-colors 257)) (:foreground "#c1c7c9" :background "#131516" :box (:color "#0d3c55" :line-width 1))) (((class color) (min-colors 89)) (:foreground "#afd7d7" :background "#131516" :box (:color "#0d3c55" :line-width 1)))))
 '(mode-line-buffer-id ((((class color) (min-colors 257)) (:inherit bold :foreground "#ecaa38")) (((class color) (min-colors 89)) (:inherit bold :foreground "#ffff00"))))
 '(show-paren-match ((((class color) (min-colors 257)) (:background "#2a5748")) (((class color) (min-colors 89)) (:background "#2a5748"))))
 '(show-paren-mismatch ((((class color) (min-colors 257)) (:background "#59355a")) (((class color) (min-colors 89)) (:background "#59355a"))))
 '(whitespace-empty ((((class color) (min-colors 257)) (:background nil :foreground "#b1951d")) (((class color) (min-colors 89)) (:background nil :foreground "#875f00"))))
 '(whitespace-indentation ((((class color) (min-colors 257)) (:background nil :foreground "#d94e1f")) (((class color) (min-colors 89)) (:background nil :foreground "#d75f00"))))
 '(whitespace-line ((((class color) (min-colors 257)) (:background nil :foreground "#ebc844")) (((class color) (min-colors 89)) (:background nil :foreground "#ffd75f"))))
 '(whitespace-newline ((((class color) (min-colors 257)) (:background nil :foreground "#ebc844")) (((class color) (min-colors 89)) (:background nil :foreground "#ffd75f"))))
 '(whitespace-space ((((class color) (min-colors 257)) (:background nil :foreground "#131516")) (((class color) (min-colors 89)) (:background nil :foreground "#131516"))))
 '(whitespace-space-after-tab ((((class color) (min-colors 257)) (:background nil :foreground "#b1951d")) (((class color) (min-colors 89)) (:background nil :foreground "#875f00"))))
 '(whitespace-space-before-tab ((((class color) (min-colors 257)) (:background nil :foreground "#b1951d")) (((class color) (min-colors 89)) (:background nil :foreground "#875f00"))))
 '(whitespace-tab ((((class color) (min-colors 257)) (:background nil)) (((class color) (min-colors 89)) (:background nil))))
 '(whitespace-trailing ((((class color) (min-colors 257)) (:background "#c02e1d" :foreground "#d94e1f")) (((class color) (min-colors 89)) (:background "#af0000" :foreground "#d94e1f"))))
 '(ffap ((((class color) (min-colors 257)) (:foreground "#c1c7c9")) (((class color) (min-colors 89)) (:foreground "#afd7d7"))))
 '(trailing-whitespace ((((class color) (min-colors 257)) :foreground nil :background "#c02e1d") (((class color) (min-colors 89)) :foreground nil :background "#af0000")))
 '(custom-link ((((class color) (min-colors 257)) :foreground "#ebc844" :underline t) (((class color) (min-colors 89)) :foreground "#ffd75f" :underline t)))
 '(default ((((class color) (min-colors 257)) (:background "#131516" :foreground "#c1c7c9")) (((class color) (min-colors 89)) (:background "#131516" :foreground "#afd7d7")))))

(provide-theme 'madhat2r)
